services:
  - type: web
    name: render-failure-logs-test-backend
    env: node
    plan: starter
    buildCommand: echo build
    startCommand: echo start
    numInstances: 1
    envVars:
      - key: MINIO_ACCESS_KEY
        fromService:
          name: render-failure-logs-test-minio
          type: pserv
          envVarKey: MINIO_ACCESS_KEY
      - key: MINIO_SECRET_KEY
        fromService:
          name: render-failure-logs-test-minio
          type: pserv
          envVarKey: MINIO_SECRET_KEY
      - key: MINIO_HOST
        fromService:
          name: render-failure-logs-test-minio
          type: pserv
          property: host
      - key: MINIO_ENDPOINT
        fromService:
          name: render-failure-logs-test-minio
          type: pserv
          property: host
      - key: MINIO_BUCKET
        value: assets

  - type: web
    name: render-failure-logs-test-minio
    env: docker
    dockerfilePath: ./minio/Dockerfile
    dockerContext: ./minio
    disk:
      name: data
      mountPath: /data
    envVars:
    - key: MINIO_ACCESS_KEY
      generateValue: true
    - key: MINIO_SECRET_KEY
      generateValue: true
